#!/bin/sh

set -e

MRUBY_INSTALL_PATH=/vagrant/devbox_tools/bin/devbox_tools_ruby

if [ ! -e "$MRUBY_INSTALL_PATH" ]
then
  cd /tmp

  wget https://github.com/mruby/mruby/archive/1.1.0.zip
  unzip 1.1.0.zip
  rm 1.1.0.zip

  cd mruby-1.1.0
  cp /vagrant/devbox_tools/support/mruby_build_config.rb build_config.rb

  make

  cp bin/mruby $MRUBY_INSTALL_PATH

  cd ..
  rm -rf mruby-1.1.0
fi
