#!/bin/sh

# This script installs mruby which is used to run the devbox tools. It
# assumes some basic tools (gcc, git, etc) are installed already.

MRUBY_INSTALL_PATH=/vagrant/devbox-tools/bin/devbox-tools-ruby
MRUBY_BUILD_CONFIG_PATH=/vagrant/devbox-tools/support/mruby_build_config.rb
MRUBY_VERSION=1.1.0
MRUBY_ARCHIVE=mruby-1.1.0.zip
MRUBY_INSTALLED_CHECKSUM_PATH=/home/vagrant/.mruby_checksum

# Only install if the version or the build config changes.
CURRENT_CHECKUM="$(echo $MRUBY_VERSION)-$(md5sum $MRUBY_BUILD_CONFIG_PATH|awk '{ print $1 }')"
INSTALLED_CHECKSUM=$(cat $MRUBY_INSTALLED_CHECKSUM_PATH 2> /dev/null)

if [ "$INSTALLED_CHECKSUM" != "$CURRENT_CHECKUM" ]
then
  rm -rf /tmp/mruby-$MRUBY_VERSION 2> /dev/null # if the previous run failed
  set -e

  cd /tmp
  wget https://github.com/mruby/mruby/archive/$MRUBY_VERSION.zip
  mv $MRUBY_VERSION.zip $MRUBY_ARCHIVE

  echo "$(curl https://raw.githubusercontent.com/postmodern/ruby-versions/master/mruby/checksums.sha1 | grep $MRUBY_ARCHIVE)" | sha1sum -c -

  unzip $MRUBY_ARCHIVE
  rm $MRUBY_ARCHIVE

  cd mruby-$MRUBY_VERSION
  cp $MRUBY_BUILD_CONFIG_PATH build_config.rb

  make

  cp bin/mruby $MRUBY_INSTALL_PATH
  echo $CURRENT_CHECKUM > $MRUBY_INSTALLED_CHECKSUM_PATH

  cd ..
  rm -rf mruby-$MRUBY_VERSION
fi
