#!/bin/bash

# Script to fetch the devbox-tools when you start vagrant.
# More info: https://github.com/joakimk/devbox-tools

# This script expects DEVBOX_TOOLS_VERSION and DEVBOX_TOOLS_REPO to be set.

set -e

if [ -e devbox-tools ]
then
  printf "\e[00;34mUpdating devbox-tools\e[00m... "
else
  printf "\e[00;34mInstalling devbox-tools\e[00m... "
  git clone $DEVBOX_TOOLS_REPO 1> /dev/null || exit 1
fi

# Ensure we don't overwrite local changes
cd devbox-tools
(git status|grep 'nothing to commit' 1> /dev/null)

if [ ! $? -eq 0 ]
then
  printf "\e[00;33mskipped\e[00m (there are uncommitted changes)\n"
else
  git pull > /dev/null || exit 1
  git reset --hard $DEVBOX_TOOLS_VERSION 1> /dev/null || exit 1
  printf "done\n"
fi
