#!/bin/bash

# Ensure we're in a repo where "devbox-tools" are available in the current path
[ -d devbox-tools ] || { echo "Expected devbox-tools to be available in the current directory"; exit 1; }

set -e
cp devbox-tools/support/Vagrantfile .
cp devbox-tools/support/README.md .

echo "devbox-tools" >> .gitignore # >> to be nice and not overwrite any previous file
echo ".vagrant" >> .gitignore
git init . > /dev/null
git add .
git commit -m "Initial commit" > /dev/null
