#!/bin/sh

if [ "$1" = "up" ]
then
  mkdir -p tmp/test && cd tmp/test && vagrant destroy -f; cd ../.. 2> /dev/null
  rm -rf tmp/test

  mkdir -p tmp/test
  cd tmp/test

  # Test that we check for devbox-tools
  ../../bootstrap | grep "Expected devbox-tools to be available" > /dev/null ||
    { echo "TEST FAIL: Check for devbox-tools failed"; exit 1; }

  # Test integration
  rsync -a --exclude="tmp" ../.. devbox-tools
  devbox-tools/bootstrap

  ls Vagrantfile 1> /dev/null ||
    { echo "TEST FAIL: Expected bootstrap to setup Vagrantfile"; exit 1; }

  ls set_up_devbox_tools 1> /dev/null ||
    { echo "TEST FAIL: Expected bootstrap to setup set_up_devbox_tools script"; exit 1; }

  cat .gitignore | grep devbox-tools > /dev/null ||
    { echo "TEST FAIL: Expected bootstrap to setup .gitignore"; exit 1; }

  git status | grep "working directory clean" > /dev/null ||
    { echo "TEST FAIL: Expected bootstrap to setup git"; exit 1; }

  RUNNING_TEST=true vagrant up
  vagrant ssh -c '/vagrant/devbox-tools/bin/devbox-tools-ruby -e "puts 20/2"' | grep "10" > /dev/null ||
    { echo "TEST FAIL: Expected working ruby after VM is setup"; exit 1; }

  # Symlink in the main tools directory so that we can edit tests
  # and re-run them inside an existing VM during development
  vagrant ssh -c "cp /vagrant/devbox-tools/bin/devbox-tools-ruby /devbox-tools/bin && rm -rf /vagrant/devbox-tools && ln -s /devbox-tools /vagrant/devbox-tools"
  cd ../..
  ./testvm test
  echo "Success!"
  exit
fi

if [ "$1" = "update" ]
then
  cd tmp/test && vagrant ssh -c '/vagrant/devbox-tools/support/install_dependencies'
  exit
fi

if [ "$1" = "ssh" ]
then
  cd tmp/test && vagrant ssh
  exit
fi

if [ "$1" = "destroy" ]
then
  cd tmp/test && vagrant destroy -f
  exit
fi

if [ "$1" = "test" ]
then
  cd tmp/test && vagrant ssh -c "find /vagrant/devbox-tools/test/*tests.rb -exec /vagrant/devbox-tools/bin/devbox-tools-ruby {} \;"
  exit
fi


if [ "$1" = "integration" ]
then
  cd tmp/test && vagrant ssh -c "/vagrant/devbox-tools/bin/devbox-tools-ruby /vagrant/devbox-tools/test/integration_tests.rb"
  exit
fi

if [ "$1" = "unit" ]
then
  cd tmp/test && vagrant ssh -c "/vagrant/devbox-tools/bin/devbox-tools-ruby /vagrant/devbox-tools/test/unit_tests.rb"
  exit
fi

echo "Usage:"
echo "./testvm up           # Start VM and run all tests"
echo "./testvm test         # Run all tests inside VM"
echo "./testvm integration  # Run integration tests inside VM"
echo "./testvm unit         # Run unit tests inside VM"
echo "./testvm ssh          # Log in to the test VM"
echo "./testvm update       # Update dependencies"
echo "./testvm destroy      # Destroy VM"
